project_id = "dnxzpkbobzwjcuyfgdnh"

[functions.cif-advisor]
verify_jwt = false

[functions.volumetric-weight-advisor]
verify_jwt = false

[functions.market-price-advisor]
verify_jwt = false

[functions.pricing-optimizer]
verify_jwt = false

[functions.create-user-direct]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.resend-invitation]
verify_jwt = false
