-- Import F&B products from CSV
-- Filtering out admin items, services, and items with 0 or empty prices

INSERT INTO fnb_products (code, name, unit, price_xcg, is_active) VALUES
-- Juices
('FOJ_1500', '1.5 Liter Fresh Orange Juice (FOJ)', '1.5L', 12, true),
('FOJ_1000', '1 Liter Fresh Orange Juice (FOJ)', '1L', 8.5, true),
('LIME_EXT_5L', '5L Lime Extract', '5L', 61.32, true),
('LIME_EXT_1L', 'Lime Extract 1L', '1L', 13.68, true),
('LEMON_EXT_1L', 'Lemon Extract 1 Liter', '1L', 30, true),

-- Berries & Fruits
('AALBES', 'Aalbes | Redcurrant', 'pack 125g', 8.85, true),
('BLACKBERRY', 'Blackberry', 'pack 170g', 11.5, true),
('BLUEBERRY', 'Blueberry', 'pack 125g', 6.95, true),
('RASPBERRY', 'Raspberries', 'pack 170g', 13.95, true),
('STRAWBERRY_500', 'Strawberry', 'box 500g', 12.95, true),
('STRAWBERRY_250', 'Strawberry 250gr', 'pack 250g', 7.95, true),
('APPLE_GALA', 'Apple Gala', 'piece', 1.65, true),
('APPLE_GRANNY', 'Apple Granny Smith', 'piece', 1.75, true),
('APPLE_JONAGOLD', 'Apple Jonagold', 'piece', 2.5, true),
('AVOCADO_KG', 'Avocado', 'kg', 7.15, true),
('AVOCADO_HASS', 'Avocado Hass', 'piece', 3.15, true),
('BANANA', 'Banana', 'kg', 4.65, true),
('CIRUELA', 'Ciruela', 'piece', 3.15, true),
('COCONUT', 'Coco/ Coconut', 'piece', 4.3, true),
('DRAGON_FRUIT', 'Dragon Fruits', 'kg', 19.65, true),
('GRAPEFRUIT', 'Grapefruit', 'kg', 7.5, true),
('GREEN_GRAPES', 'Green Grapes | Druif', 'kg', 19.95, true),
('RED_GRAPES', 'Red Grapes | Druif', 'kg', 14.5, true),
('GUAVA', 'Guava', 'kg', 6.25, true),
('GUYABA', 'Guyaba', 'kg', 5.85, true),
('KIWI', 'Kiwi', 'kg', 22.95, true),
('LEMON', 'Lemon', 'kg', 7.15, true),
('LIME', 'Lime', 'kg', 5.35, true),
('LIME_SLICED', 'Sliced Lime', 'kg', 6.05, true),
('MANGO', 'Mango', 'kg', 6.25, true),
('MELON_CANT', 'Melon Cantaloupe', 'kg', 7.95, true),
('MELON_HONEY', 'Melon Honey Dew', 'kg', 7.5, true),
('ORANGE_CREOLE', 'Orange Creole', 'kg', 3.45, true),
('ORANGE_USA', 'Orange USA', 'kg', 5.15, true),
('PAPAYA', 'Papaya', 'kg', 3.65, true),
('PASSION_FRUIT', 'Passion Fruit', 'kg', 6.25, true),
('PASSION_GULUPA', 'PassionFruit Gulupa', 'kg', 14.25, true),
('PEACH', 'Peach', 'kg', 8.95, true),
('PEAR', 'Pear', 'piece', 1.25, true),
('PINEAPPLE', 'Pineapple', 'piece', 6.95, true),
('PLANTAIN', 'Plantain', 'kg', 4.65, true),
('PLUM', 'Plum', 'kg', 13.75, true),
('POMEGRANATE', 'Pomgranate Holland', 'piece', 16.5, true),
('TANGERINE', 'Tangerine/Mandarijn', 'kg', 7.85, true),
('WATERMELON', 'Watermelon', 'kg', 2.75, true),

-- Vegetables
('AJI_AMARILLO', 'Aji Amarillo', '5LB', 231.55, true),
('AJI_AMARILLO_PASTE', 'Aji Amarillo Paste', '7.5oz', 35.75, true),
('AJI_DULCE', 'Aji dulce', 'kg', 9.95, true),
('AJI_PANCA', 'Aji Panca Black', '5LB', 231.55, true),
('AJI_PANCA_PASTE', 'Aji Panca Paste', '7.5oz', 35.25, true),
('ARUGULA', 'Arugula', 'piece', 6, true),
('ARUGULA_PACK', 'Arugula Pack', 'pack', 5, true),
('ASPARAGUS', 'Asparagus', 'kg', 25.5, true),
('AUBERGINE', 'Aubergine', 'piece', 3.5, true),
('BABY_CUCUMBER', 'Baby Cucumber', 'kg', 5, true),
('BABY_MIX_SALAD', 'Baby Mix Salad', 'pack 150g', 6.15, true),
('BABY_POTATO', 'Baby Potato', 'kg', 6.25, true),
('BABY_RUCOLA', 'Baby Rucola', 'pack 150g', 6.15, true),
('BABY_RUCOLA_KG', 'Baby Rucola Kg', 'kg', 39.95, true),
('BABY_SPINACH', 'Baby Spinach', 'pack 150g', 6.15, true),
('BEETROOT', 'Beetroot', 'kg', 9.65, true),
('BOK_CHOY', 'Bok Choy', 'piece', 2.5, true),
('BOSTON_LETTUCE', 'Boston Lettuce', 'piece', 8.05, true),
('BROCCOLI', 'Broccoli', 'kg', 17.95, true),
('BUTTERHEAD', 'ButterHead', 'piece', 3.85, true),
('BUTTERNUT', 'Butternut Squash', 'kg', 10.55, true),
('CABBAGE', 'Cabbage | Kool', 'piece', 4.15, true),
('CARROT', 'Carrot', 'kg', 6, true),
('CARROTS', 'Carrots', 'kg', 4.75, true),
('CARROTS_SLICED', 'Carrots Slices', 'kg', 8.95, true),
('CAULIFLOWER', 'Cauliflower', 'piece', 13.95, true),
('CELERY', 'Celery', 'piece', 7.95, true),
('CELERY_BUNCH', 'Celery Bunch', 'bunch', 2, true),
('CELERY_USA', 'Celery USA', 'kg', 7.95, true),
('CHARD', 'Chard', 'bunch', 2, true),
('CHAYOTE', 'Chayote', 'kg', 3.95, true),
('CHERRY_TOM_500', 'Cherry Tomatoes Large Red', '500g', 13.5, true),
('CHERRY_TOM_250', 'Cherry Tomatoes Large Red 250 gr', '250g', 4.95, true),
('CHILE_ANCHO', 'Chile Ancho', '5LB', 166.95, true),
('CHILE_ANCHO_PACK', 'Chile Ancho Pack', '1LB', 45, true),
('CHILE_CHIPOTLE', 'Chile Chipotle', '5LB', 183.5, true),
('CHILE_CHIPOTLE_PACK', 'Chile Chipotle Pack', '1LB', 48.75, true),
('CHILE_GUAJILLO', 'Chile Guajillo', '5LB', 158.35, true),
('CHILE_GUAJILLO_PACK', 'Chile Guajillo Pack', '1LB', 45, true),
('CORN', 'Corn', 'piece', 1.8, true),
('CUCUMBER', 'Cucumber', 'piece', 3.15, true),
('FENNEL', 'Fennel', 'kg', 18.65, true),
('GARLIC', 'Garlic', 'kg', 10.25, true),
('GARLIC_PEELED', 'Garlic Peeled', 'kg', 33.5, true),
('GINGER', 'Ginger', 'kg', 12.5, true),
('GREEN_CHILI', 'Green Chili', 'pack 100g', 2.95, true),
('GREEN_SALAD', 'Green Salad', 'piece', 4.65, true),
('HARICOTS', 'Haricots', 'pack 250g', 8.85, true),
('ICEBERG', 'Iceberg Lettuce', 'head', 4.95, true),
('JALAPENO', 'Jalapeno', 'pack 100g', 4.35, true),
('KALE', 'Kale', 'piece', 9.65, true),
('KOUSEBAND', 'Kouseband', 'kg', 5.5, true),
('LEEK', 'Leek', 'piece', 7.95, true),
('LITTLE_GEMS', 'Little Gems', 'piece', 7.75, true),
('LOLLO_BIONDO', 'Lollo Biondo', 'piece', 3.85, true),
('LOLLO_ROSSO', 'Lollo Rosso', 'piece', 3.95, true),
('MADAME_JEANETTE', 'Madame Jeanette', 'piece', 16.95, true),
('MALANGA', 'Malanga', 'kg', 4.15, true),
('MESCLUN_MIX', 'Mesclun Mix', 'pack 150g', 6.15, true),
('MESCLUN_CASE', 'Lettuce Mesclum Case(24)', 'case', 70.8, true),
('MUSHROOM_PACK', 'Mushrooms', 'pack 250g', 7.5, true),
('MUSHROOM_KG', 'Mushroom White', 'kg', 18.75, true),
('OAK_GREEN', 'Oak Green Salad', 'piece', 5.95, true),
('OKRA', 'Okra', 'piece', 6.15, true),
('ONION', 'Onion', 'kg', 2.75, true),
('RED_ONION', 'Red Onion', 'kg', 3.95, true),
('WHITE_ONION', 'White Onion', 'kg', 5.35, true),
('PAKSOY', 'Paksoy', 'piece', 1.95, true),
('PAPRIKA_GREEN', 'Paprika Green', 'kg', 6.25, true),
('PAPRIKA_ORANGE', 'Paprika Orange', 'kg', 12.5, true),
('PAPRIKA_RED', 'Paprika Red', 'kg', 8.95, true),
('PAPRIKA_YELLOW', 'Paprika Yellow', 'kg', 12.5, true),
('PARSNIP', 'Parsnip', 'bag', 9.35, true),
('POTATO_COL', 'Potato/Col', 'kg', 4.15, true),
('POTATO_HOLLAND', 'Potato Holland', 'kg', 2.35, true),
('PUMPKIN', 'Pumpkin', 'piece', 2.75, true),
('RADISH', 'Radish', 'pack 170g', 3.25, true),
('RED_CABBAGE', 'Red Cabbage | Rode Kool', 'piece', 6.95, true),
('RED_CABBAGE_SLICE', 'Red Cabbage Slice', 'kg', 8.95, true),
('RED_CHILI', 'Red Chili', 'pack 100g', 2.95, true),
('ROMAINE', 'Romaine Salad', 'piece', 3.95, true),
('SJALOTTEN', 'Sjalotten', 'kg', 15.45, true),
('SPINACH_SAVOY', 'Spinach Savoy Leaves | Spinazie', 'piece', 4.3, true),
('SPRING_ONION', 'Spring Onion', 'piece', 2, true),
('SUGAR_PEA', 'Sugar Pea bean', 'kg', 25.25, true),
('SWEET_POTATO', 'Sweet Potato', 'kg', 7.75, true),
('TAUGE', 'Tauge', 'kg', 6.5, true),
('TOMATO_PERITA', 'Tomato Perita', 'kg', 6.25, true),
('TOMATO_RONDO', 'Tomato Rondo', 'kg', 6.75, true),
('TURMERIC', 'Turmeric', 'kg', 17.95, true),
('VINE_CHERRY_TOM', 'Vine Red Ripened Cherry Tomato', 'pack', 14.1, true),
('YUCCA', 'Yucca', 'piece', 14.95, true),
('ZUCCHINI', 'Zucchini', 'kg', 7.95, true),
('ZUCCHINI_YELLOW', 'Yellow Zucchini', 'kg', 8.95, true),

-- Herbs
('ALFALFA', 'Alfalfa', 'pack', 3.25, true),
('AMARANTH', 'Amaranth', 'pack', 5, true),
('AMARANTH_RED', 'Amaranth, Red Garnet', 'pack', 6, true),
('ANISE', 'Anise', 'pack', 6, true),
('BASIL_POTS', 'Basil', 'pot', 13.95, true),
('BASIL_BOX', 'Basil Box', 'box', 11, true),
('BASIL_BUNCH', 'Basil Bunch', 'bunch', 2, true),
('BASIL_DARK_OPAL', 'Basil, Dark Opal', 'pack', 6, true),
('BASIL_ITALIAN', 'Basil, Italian Large Leaf', 'pack', 6, true),
('BASIL_KG', 'Basil Kg', 'kg', 40, true),
('BASIL_PACK', 'Basil Pack', 'pack', 2, true),
('BASIL_RED', 'Basil, Red Rubin', 'pack', 6, true),
('BASIL_PURPLE', 'Purple Basil', 'kg', 40, true),
('BASIL_THAI', 'Thai Basil', 'kg', 40, true),
('BASIL_LEMON', 'Lemon Basil', 'pack', 8, true),
('BASIL_LEMON_KG', 'Lemon Basil kg', 'kg', 40, true),
('BASIL_LEMON_PACK', 'Lemon Basil Pack', 'pack', 2, true),
('BASIL_ITALIAN_ED', 'Italian Basil', 'edible flower', 0.5, true),
('BASIL_ITALIAN_PACK', 'Italian Basil Pack', 'pack', 5, true),
('BAY_LEAVES', 'Bay Leaves', 'pack', 2, true),
('BAY_LEAVES_KG', 'Bay Leaves Kg', 'kg', 82.5, true),
('BORAGE', 'Borage', 'pack', 12, true),
('BUCKWHEAT', 'Buckwheat', 'pack', 6, true),
('CALENDULA', 'Calendula', 'pack', 2, true),
('CAMOMILE', 'Camomile', 'pack', 2, true),
('CHIVES', 'Chives', 'edible flower', 1, true),
('CHIVES_KG', 'Chives Kg', 'kg', 40, true),
('CHIVES_PACK', 'Chives Pack', 'pack', 2, true),
('CILANTRO_BOX', 'Cilantro Box', 'box', 11, true),
('CILANTRO_BUNCH', 'Cilantro Bunch', 'bunch', 2, true),
('CILANTRO_KG', 'Cilantro Kg', 'kg', 40, true),
('CILANTRO_LEISURE', 'Cilantro, Leisure Splits', 'pack', 8, true),
('CILANTRO_PACK', 'Cilantro Pack', 'pack', 2, true),
('CILANTRO_POTS', 'Cilantro Pots', 'pot', 13.95, true),
('CRESS_CURLED', 'Cress , Curled', 'pack', 6, true),
('DILL', 'Dill', 'pack', 6, true),
('DILL_BOX', 'Dill Box', 'box', 11, true),
('DILL_FLOWER', 'Dill Flower', 'edible flower', 15, true),
('DILL_KG', 'Dill Kg', 'kg', 40, true),
('DILL_PACK', 'Dill Pack', 'pack', 2, true),
('EUCALYPTUS', 'Eucalyptus', 'pack', 2, true),
('GUASCA', 'Guasca', 'pack', 2, true),
('LAUREL', 'Laurel', 'kg', 85, true),
('LEMONGRASS_BOX', 'Lemongrass Box', 'box', 11, true),
('LEMONGRASS_BUNCH', 'Lemongrass Bunch', 'bunch', 2, true),
('LEMONGRASS_KG', 'Lemongrass Kg', 'kg', 40, true),
('LEMONGRASS_PACK', 'Lemongrass Pack', 'pack', 2, true),
('LIPIA_ALBA', 'Lipia Alba', 'kg', 40, true),
('LIPIA_ALBA_BOX', 'Lippia Alba Box', 'box', 11, true),
('LIPIA_ALBA_KG', 'Lippia Alba Kg', 'kg', 40, true),
('LIPIA_ALBA_PACK', 'Lippia Alba Pack', 'pack', 2, true),
('MARJORAM', 'Marjoram', 'pack', 2, true),
('MINT_POTS', 'Mint', 'pot', 13.95, true),
('MINT_BOX', 'Mint Box', 'box', 11, true),
('MINT_BUNCH', 'Mint Bunch', 'bunch', 2, true),
('MINT_KG', 'Mint Kg', 'kg', 40, true),
('MINT_PACK', 'Mint Pack', 'pack', 2, true),
('MORINGA', 'Moringa', 'pack', 2, true),
('MUSTARD', 'Mustard', 'pack', 5, true),
('MUSTARD_RED', 'Mustard, Red Garnet', 'pack', 6, true),
('MIZUNA', 'Mizuna', 'pack', 5, true),
('MIZUNA_MUSTARD', 'Mizuna (Mustard)', 'pack', 6, true),
('OREGANO', 'Oregano', 'pack', 2, true),
('OREGANO_BOX', 'Oregano Box', 'box', 11, true),
('OREGANO_BUNCH', 'Oregano Bunch', 'bunch', 2, true),
('OREGANO_KG', 'Oregano Kg', 'kg', 40, true),
('PARSLEY_BOX', 'Parsley', 'box', 11, true),
('PARSLEY_BUNCH', 'Parsley Bunch', 'bunch', 2, true),
('PARSLEY_ITALIAN', 'Parsley ITALIAN (plat)', 'pack', 2, true),
('PARSLEY_KG', 'Parsley Kg', 'kg', 40, true),
('PARSLEY_PACK', 'Parsley Pack', 'pack', 2, true),
('PEPPERMINT', 'Peppermint', 'pack', 2, true),
('PEPPERMINT_BOX', 'Peppermint Box', 'box', 11, true),
('PEPPERMINT_KG', 'Peppermint Kg', 'kg', 40, true),
('ROMERO', 'Romero', 'pack', 2, true),
('ROSEMARY', 'Rosemary', 'kg', 40, true),
('RUDA', 'Ruda', 'pack', 2, true),
('RUDA_KG', 'Ruda Kg', 'kg', 40, true),
('SAGE', 'Sage', 'kg', 40, true),
('SAGE_PACK', 'Sage Pack', 'pack', 2, true),
('SELDER_KORSOU', 'Selder di Korsou', 'kg', 2, true),
('TARRAGON', 'Tarragon', 'pack', 2, true),
('THYME_POTS', 'Thyme', 'pot', 13.95, true),
('THYME_BOX', 'Thyme Box', 'box', 11, true),
('THYME_KG', 'Thyme Kg', 'kg', 40, true),
('THYME_PACK', 'Thyme Pack', 'pack', 2, true),
('YERBI_HOLE', 'Yerb''i  Hole', 'pack', 2, true),

-- Premium & Microgreens
('BEET_BULLS', 'Beet, Bull''s Blood', 'pack', 6, true),
('BEET_SWISS', 'Beet, Swiss Chard', 'pack', 6, true),
('BROCCOLI_WALTHAM', 'Broccoli, Waltham 29', 'pack', 6, true),
('FRILLS_MUSTARD', 'Frills Mustard', 'pack', 6, true),
('GOLD_CORN', 'Gold Corn', 'pack', 8, true),
('GREEN_CORN', 'Green Corn', 'pack', 8, true),
('GREEN_RADISH', 'Green Radish', 'pack', 5, true),
('KOHLRABI_PURPLE', 'Kohlrabi, Purple Vienna', 'pack', 6, true),
('MIX_MICRO', 'Mix', 'pack', 6, true),
('MIX_AMAR_CRESS', 'Mix Amaranth & Cress', 'pack', 6, true),
('MIX_AMAR_MIZUNA', 'Mix Amaranth & Mizuna', 'pack', 6, true),
('MIX_AMAR_MUSTARD', 'Mix Amaranth & Mustard', 'pack', 6, true),
('MIX_RADISH', 'Mix Radish', 'pack', 6, true),
('NASTURTIUM', 'Nasturtium, Jewel Mix', 'pack', 8, true),
('PEA_SNOW', 'Pea, Snow Mammoth Meltin Sugar Pot', 'pack', 8, true),
('RADISH_RED_ARROW', 'Radish, Red Arrow', 'pack', 6, true),
('RADISH_RED_RAMBO', 'Radish, Red Rambo', 'pack', 6, true),
('RED_RADISH', 'Red Radish', 'pack', 5, true),
('SHISO_PERILLA', 'Shiso, Perilla Purple', 'pack', 12, true),
('SHUNGIKU', 'Shungiku', 'pack', 8, true),
('SORREL_RED', 'Sorrel, Red Veined', 'pack', 12, true),
('SPICY_SALAD', 'Spicy Salad Mix (microgreens)', 'pack', 6, true),
('SUNFLOWER_BLACK', 'Sunflower, Black Oil', 'pack', 6, true),
('TENDRIL', 'Tendril', 'pack', 5, true),
('TENDRIL_PEA', 'Tendril Pea, Yellow', 'pack', 6, true),
('WHEAT_HARD', 'Wheat, Hard Red Spring', 'pack', 6, true),

-- Dried Products
('DRIED_LIME', 'Dried Lime Fruits', 'gram', 0.12, true),
('DRIED_ORANGE', 'Dried Orange', 'gram', 0.1, true),
('DRIED_PINEAPPLE', 'Dried Pineapple', 'gram', 0.14, true),

-- Other Products
('CHIA_SEEDS', 'Chia seeds', 'pack', 19.85, true),
('EDIBLE_FLOWERS', 'Edible Flowers Mix', 'pack', 22.8, true),
('EGGS', 'Eggs', 'palette', 16, true),
('FROZEN_PEAS', 'Frozen Peas', 'kg', 14.7, true),
('JAMAICAN_FLOWER', 'Jamaican flower', 'pack', 10, true),
('PAISA', 'Paisa', 'kg', 26, true),
('PANELA', 'Panela', 'pack 400g', 2.65, true),
('PARCHITA_PULP', 'Parchita Pulp', 'pack', 23.5, true),
('POTGROND', 'Potgrond', '40L', 16.95, true),
('SUNFLOWER_FO', 'Sunflower FO', 'piece', 83.5, true),
('TAMARIN_PULP', 'Tamarin Pulp', '500g', 6.25, true),
('UCHUVAS', 'Uchuvas', 'pack 100g', 4, true),
('ZUURZAAK', 'ZUURZAAK', 'piece', 7.25, true),
('PLASTIC_BOTTLES', 'Plastic Bottles 1.5L', 'piece', 1.5, true)

ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  unit = EXCLUDED.unit,
  price_xcg = EXCLUDED.price_xcg,
  updated_at = now();